### ISSUE TITLE
So Many Buckets!?

### ISSUE THREAD

**Issue by kristin-at-theta** [CMSgov/macpro-quickstart-serverless#91] opened 2020-10-28 20:21 UTC
Seven buckets per deployment kind of seems like a lot?
The following might be useful --
```
If you have defined multiple buckets, you can limit your deployment to a single bucket with the --bucket option:
$ sls s3deploy --bucket my-bucket
```
The ultimate goal is not running into that account bucket limit... it will help a lot to get moving to a CI where the destroy is automatically happening, but even with decent cleanup, it only takes 14 branches to blow the limit...  I count 6 people already making branches, with at least 3 more onboarding this quarter...  

Let's please optimize the bucket usage and cleanup :)

**Comment by mdial89f** [comment] 2020-10-28 20:28
Closing as duplicate of #12
I'm going to copy/paste your comments over there.

**Closed by mdial89f** 2020-10-28 20:28 UTC
